name: Lint Python

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: chrysoptera-stack/api
        run: |
          pip install -r requirements.txt
          pip install flake8

      - name: Run flake8 lint check
        working-directory: chrysoptera-stack/api
        run: flake8 main.py --max-line-length=100